import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#04131f',
  },
  lottieBackgroundWrap: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  lottieBackground: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  stageShell: {
    flex: 1,
    paddingTop: 56,
    paddingBottom: 104,
  },
  stage: {
    flex: 1,
    zIndex: 1,
  },
  robotStagePressable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  robotStageStack: {
    width: '82%',
    height: '66%',
    maxWidth: 520,
    maxHeight: 520,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  robotStageOverlayLottie: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  robotStageLottie: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 2,
  },
  webview: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  loader: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loaderText: {
    color: '#daf7f1',
    fontSize: 15,
    fontWeight: '600',
  },
  statusBanner: {
    position: 'absolute',
    top: 18,
    left: 16,
    right: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    zIndex: 20,
    elevation: 20,
  },
  statusText: {
    color: '#dbfaf5',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  foregroundScreen: {
    ...StyleSheet.absoluteFillObject,
    top: 64,
    bottom: 84,
    left: 8,
    right: 8,
    zIndex: 18,
  },
  assistantScreen: {
    ...StyleSheet.absoluteFillObject,
    top: 56,
    bottom: 18,
    left: 8,
    right: 8,
    zIndex: 18,
  },
  screenCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.1)',
    padding: 12,
  },
  screenHeader: {
    marginBottom: 10,
  },
  chatHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  chatHeaderTextWrap: {
    flex: 1,
  },
  chatMenuButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatMenuButtonText: {
    color: '#dffcf6',
    fontSize: 14,
    fontWeight: '800',
    transform: [{ rotate: '90deg' }],
  },
  screenTitle: {
    color: '#f3fffd',
    fontSize: 20,
    fontWeight: '800',
  },
  screenSubtitle: {
    color: '#96c6be',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  homeVoiceDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 92,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    zIndex: 18,
  },
  assistantCardShell: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  assistantPanel: {
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 10,
    gap: 10,
  },
  assistantTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  assistantTopText: {
    flex: 1,
    gap: 2,
  },
  assistantTitle: {
    color: '#f3fffd',
    fontSize: 18,
    fontWeight: '800',
  },
  assistantSubtitle: {
    color: '#96c6be',
    fontSize: 11,
    lineHeight: 16,
  },
  assistantActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  assistantActionButton: {
    minHeight: 38,
    minWidth: 38,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  assistantActionButtonPrimary: {
    backgroundColor: '#14b8a6',
    borderColor: '#14b8a6',
  },
  assistantActionButtonText: {
    color: '#dffcf6',
    fontSize: 12,
    fontWeight: '700',
  },
  assistantActionButtonTextPrimary: {
    color: '#052f2d',
  },
  assistantChatWrap: {
    height: '58%',
    minHeight: 300,
    maxHeight: 470,
  },
  assistantVoiceDock: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 4,
  },
  voiceWaveWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceWaveButton: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceWaveAnimation: {
    width: 112,
    height: 112,
  },
  voiceWaveLabel: {
    color: '#dffcf6',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatMessages: {
    flex: 1,
  },
  chatMessagesContent: {
    gap: 8,
    paddingBottom: 10,
  },
  chatBubble: {
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 5,
    maxWidth: '96%',
  },
  chatBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(20, 184, 166, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.18)',
  },
  chatBubbleAssistant: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.1)',
  },
  chatBubbleRole: {
    color: '#8fe5d8',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  chatBubbleText: {
    color: '#eef9ff',
    fontSize: 12,
    lineHeight: 18,
  },
  chatImage: {
    width: 150,
    height: 106,
    borderRadius: 10,
    backgroundColor: '#0f172a',
  },
  chatImagePressable: {
    alignSelf: 'flex-start',
    borderRadius: 10,
    overflow: 'hidden',
  },
  chatComposer: {
    marginTop: 10,
    gap: 8,
  },
  chatAttachmentCard: {
    gap: 8,
    borderRadius: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 10,
  },
  chatAttachmentPreview: {
    width: '100%',
    height: 154,
    borderRadius: 10,
    backgroundColor: '#0f172a',
  },
  chatInput: {
    minHeight: 88,
    maxHeight: 132,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    color: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
    fontSize: 13,
  },
  chatActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chatPrimaryButton: {
    flexGrow: 1,
    flexBasis: '48%',
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#14b8a6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  chatPrimaryButtonWide: {
    flexBasis: '100%',
  },
  chatSecondaryButton: {
    flexGrow: 1,
    flexBasis: '48%',
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  chatPrimaryButtonDisabled: {
    opacity: 0.7,
  },
  chatPrimaryButtonText: {
    color: '#052f2d',
    fontSize: 13,
    fontWeight: '800',
  },
  chatSecondaryButtonText: {
    color: '#dffcf6',
    fontSize: 13,
    fontWeight: '700',
  },
  imagePreviewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.86)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 32,
  },
  imagePreviewBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  imagePreviewCard: {
    width: '100%',
    maxWidth: 720,
    maxHeight: '88%',
    borderRadius: 24,
    backgroundColor: 'rgba(6, 15, 27, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 14,
    gap: 14,
  },
  imagePreviewImage: {
    width: '100%',
    height: 420,
    maxHeight: '82%',
    borderRadius: 18,
    backgroundColor: '#020617',
  },
  imagePreviewActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  tabRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  tabRowWrap: {
    marginBottom: 10,
  },
  tabGridThree: {
    flexDirection: 'row',
    gap: 8,
  },
  tabBtn: {
    flex: 1,
    minHeight: 42,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  tabBtnActive: {
    backgroundColor: '#14b8a6',
    borderColor: '#14b8a6',
  },
  tabBtnText: {
    color: '#dbe7f2',
    fontSize: 12,
    fontWeight: '700',
  },
  tabBtnTextActive: {
    color: '#042f2e',
  },
  sectionTitle: {
    color: '#8fe5d8',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  list: {
    flex: 1,
  },
  listContent: {
    gap: 10,
    paddingBottom: 12,
  },
  bgPreviewCard: {
    height: 88,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
  },
  bgPreviewCardActive: {
    borderColor: '#2dd4bf',
    borderWidth: 2,
  },
  bgPreviewLottie: {
    width: '100%',
    height: '100%',
    opacity: 0.54,
  },
  bgPreviewOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(2, 6, 23, 0.18)',
  },
  bgPreviewText: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '700',
  },
  modelBtn: {
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  modelBtnActive: {
    borderColor: '#14b8a6',
    backgroundColor: 'rgba(20, 184, 166, 0.16)',
  },
  modelBtnText: {
    color: '#edf7ff',
    fontSize: 14,
    fontWeight: '700',
  },
  modelBtnTextActive: {
    color: '#c9fff6',
  },
  itemBtn: {
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  itemBtnActive: {
    backgroundColor: 'rgba(20, 184, 166, 0.18)',
    borderWidth: 1,
    borderColor: '#14b8a6',
  },
  itemText: {
    color: '#dce8f2',
    fontSize: 13,
  },
  itemTextActive: {
    color: '#d8fff8',
    fontWeight: '700',
  },
  emptyState: {
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  emptyStateText: {
    color: '#b9cad8',
    fontSize: 13,
    lineHeight: 20,
  },
  cameraScreen: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 18,
    elevation: 18,
    backgroundColor: '#020617',
  },
  assistantCameraTopBar: {
    position: 'absolute',
    top: 18,
    left: 12,
    right: 12,
    zIndex: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  liveCameraPreview: {
    flex: 1,
  },
  liveCameraPermissionBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 14,
  },
  liveCameraTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  liveCameraHint: {
    color: '#d1f5ef',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    maxWidth: 320,
  },
  cameraHud: {
    position: 'absolute',
    top: 84,
    left: 18,
    right: 18,
    alignItems: 'center',
    gap: 6,
  },
  cameraVoiceDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 118,
    alignItems: 'center',
  },
  bottomNav: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 12,
    flexDirection: 'row',
    gap: 6,
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(6, 15, 27, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.1)',
    zIndex: 25,
    elevation: 25,
  },
  bottomNavButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.76)',
  },
  bottomNavButtonActive: {
    backgroundColor: '#14b8a6',
  },
  bottomNavText: {
    color: '#dbedf7',
    fontSize: 11,
    fontWeight: '700',
  },
  bottomNavTextActive: {
    color: '#052f2d',
  },
  lipSyncButton: {
    position: 'absolute',
    right: 16,
    top: 78,
    backgroundColor: 'rgba(15, 118, 110, 0.96)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    zIndex: 22,
    elevation: 22,
  },
  lipSyncButtonText: {
    color: '#ecfeff',
    fontSize: 11,
    fontWeight: '700',
  },
  ttsPanel: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 72,
    backgroundColor: 'rgba(6, 15, 27, 0.96)',
    borderRadius: 20,
    padding: 14,
    zIndex: 35,
    elevation: 35,
    gap: 8,
  },
  ttsTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  ttsLabel: {
    color: '#c7dbeb',
    fontSize: 12,
    fontWeight: '700',
  },
  ttsInput: {
    minHeight: 92,
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    color: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  speakerRow: {
    gap: 8,
    paddingRight: 8,
  },
  speakerChip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
  },
  speakerChipActive: {
    backgroundColor: '#14b8a6',
  },
  speakerChipText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '700',
  },
  speakerChipTextActive: {
    color: '#042f2e',
  },
  ttsButton: {
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: '#14b8a6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ttsButtonDisabled: {
    opacity: 0.7,
  },
  ttsButtonText: {
    color: '#042f2e',
    fontSize: 14,
    fontWeight: '800',
  },
  authOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    backgroundColor: 'rgba(2, 6, 23, 0.7)',
    zIndex: 40,
  },
  authCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 16,
    gap: 10,
  },
  authTitle: {
    color: '#f3fffd',
    fontSize: 22,
    fontWeight: '800',
  },
  authSubtitle: {
    color: '#96c6be',
    fontSize: 13,
    lineHeight: 19,
  },
  authModeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  authModeButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authModeButtonActive: {
    backgroundColor: '#14b8a6',
    borderColor: '#14b8a6',
  },
  authModeText: {
    color: '#dffcf6',
    fontSize: 13,
    fontWeight: '700',
  },
  authModeTextActive: {
    color: '#042f2e',
  },
  authInput: {
    minHeight: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    color: '#f8fafc',
    paddingHorizontal: 14,
    fontSize: 14,
  },
  authPrimaryButton: {
    minHeight: 46,
    borderRadius: 10,
    backgroundColor: '#14b8a6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authPrimaryButtonText: {
    color: '#042f2e',
    fontSize: 14,
    fontWeight: '800',
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.72)',
    justifyContent: 'center',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  drawerPanel: {
    width: '90%',
    maxWidth: 340,
    height: '88%',
    marginLeft: 8,
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 12,
    gap: 10,
  },
  drawerTitle: {
    color: '#f3fffd',
    fontSize: 20,
    fontWeight: '800',
  },
  drawerSubtitle: {
    color: '#96c6be',
    fontSize: 12,
    fontWeight: '600',
  },
  profileCard: {
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.08)',
    padding: 10,
    gap: 8,
  },
  profileLabel: {
    color: '#dffcf6',
    fontSize: 12,
    fontWeight: '700',
  },
  profileInput: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: 'rgba(6, 15, 27, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    color: '#f8fafc',
    paddingHorizontal: 12,
    fontSize: 14,
  },
  profileCodeLabel: {
    color: '#9fc6c0',
    fontSize: 12,
    lineHeight: 18,
  },
  settingsProfileSection: {
    marginBottom: 12,
    gap: 8,
  },
  settingsActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  settingsPrimaryButton: {
    flex: 1,
  },
  drawerCompactButton: {
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: '#14b8a6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  drawerCompactButtonText: {
    color: '#052f2d',
    fontSize: 13,
    fontWeight: '800',
  },
  drawerLogoutButton: {
    alignSelf: 'flex-start',
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  drawerLogoutButtonText: {
    color: '#dffcf6',
    fontSize: 12,
    fontWeight: '700',
  },
  drawerList: {
    flex: 1,
  },
  drawerListContent: {
    gap: 10,
    paddingBottom: 10,
  },
  drawerItem: {
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.08)',
    padding: 10,
    gap: 4,
  },
  drawerItemActive: {
    borderColor: '#14b8a6',
    backgroundColor: 'rgba(20, 184, 166, 0.16)',
  },
  drawerItemTitle: {
    color: '#eef9ff',
    fontSize: 13,
    fontWeight: '700',
  },
  drawerItemSubtitle: {
    color: '#9fc6c0',
    fontSize: 11,
    lineHeight: 16,
  },
  codeCard: {
    marginHorizontal: 16,
    borderRadius: 18,
    backgroundColor: 'rgba(6, 15, 27, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.12)',
    padding: 16,
    gap: 12,
  },
  codeTitle: {
    color: '#f3fffd',
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  codeValue: {
    color: '#5eead4',
    fontSize: 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  codeHint: {
    color: '#96c6be',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
});
