import { model6EmotionProfile, modelEmotionProfile } from './live2d/emotionProfiles';

export const live2dModels = {
  model: {
    key: 'model',
    renderer: 'live2d',
    label: 'Клара',
    characterName: 'Клара',
    displayScale: 1.5,
    gender: 'female',
    greeting: 'Привет, я Клара. Можешь написать мне, отправить картинку или задать вопрос голосом.',
    ttsSpeaker: 'kseniya',
    emotionProfile: modelEmotionProfile,
    webBase: '/live2d/model',
    modelJsonPath: 'assets/live2d/model/ulvm2_0001.model3.json',
    modelJson: require('../assets/live2d/model/ulvm2_0001.model3.json'),
    mocPath: 'assets/live2d/model/ulvm2_0001.moc3',
    moc: require('../assets/live2d/model/ulvm2_0001.moc3'),
    physicsPath: 'assets/live2d/model/ulvm2_0001.physics3.json',
    physics: require('../assets/live2d/model/ulvm2_0001.physics3.json'),
    displayInfoPath: 'assets/live2d/model/ulvm2_0001.cdi3.json',
    displayInfo: require('../assets/live2d/model/ulvm2_0001.cdi3.json'),
    texturePaths: [
      'assets/live2d/model/ulvm2_0001.4096/texture_00.png',
      'assets/live2d/model/ulvm2_0001.4096/texture_01.png',
      'assets/live2d/model/ulvm2_0001.4096/texture_02.png',
      'assets/live2d/model/ulvm2_0001.4096/texture_03.png',
      'assets/live2d/model/ulvm2_0001.4096/texture_04.png',
    ],
    textures: [
      require('../assets/live2d/model/ulvm2_0001.4096/texture_00.png'),
      require('../assets/live2d/model/ulvm2_0001.4096/texture_01.png'),
      require('../assets/live2d/model/ulvm2_0001.4096/texture_02.png'),
      require('../assets/live2d/model/ulvm2_0001.4096/texture_03.png'),
      require('../assets/live2d/model/ulvm2_0001.4096/texture_04.png'),
    ],
    expressions: [
      { fileName: 'angry.exp3.json', name: 'angry', path: 'assets/live2d/model/animation/angry.exp3.json', json: require('../assets/live2d/model/animation/angry.exp3.json') },
      { fileName: 'angry2.exp3.json', name: 'angry2', path: 'assets/live2d/model/animation/angry2.exp3.json', json: require('../assets/live2d/model/animation/angry2.exp3.json') },
      { fileName: 'blush.exp3.json', name: 'blush', path: 'assets/live2d/model/animation/blush.exp3.json', json: require('../assets/live2d/model/animation/blush.exp3.json') },
      { fileName: 'cat_mouth.exp3.json', name: 'cat_mouth', path: 'assets/live2d/model/animation/cat_mouth.exp3.json', json: require('../assets/live2d/model/animation/cat_mouth.exp3.json') },
      { fileName: 'costume_v0000.exp3.json', name: 'costume_v0000', path: 'assets/live2d/model/animation/costume_v0000.exp3.json', json: require('../assets/live2d/model/animation/costume_v0000.exp3.json') },
      { fileName: 'costume_v0052.exp3.json', name: 'costume_v0052', path: 'assets/live2d/model/animation/costume_v0052.exp3.json', json: require('../assets/live2d/model/animation/costume_v0052.exp3.json') },
      { fileName: 'costume_v0100.exp3.json', name: 'costume_v0100', path: 'assets/live2d/model/animation/costume_v0100.exp3.json', json: require('../assets/live2d/model/animation/costume_v0100.exp3.json') },
      { fileName: 'costume_v0101.exp3.json', name: 'costume_v0101', path: 'assets/live2d/model/animation/costume_v0101.exp3.json', json: require('../assets/live2d/model/animation/costume_v0101.exp3.json') },
      { fileName: 'cry.exp3.json', name: 'cry', path: 'assets/live2d/model/animation/cry.exp3.json', json: require('../assets/live2d/model/animation/cry.exp3.json') },
      { fileName: 'fx_1_heart.exp3.json', name: 'fx_1_heart', path: 'assets/live2d/model/animation/fx_1_heart.exp3.json', json: require('../assets/live2d/model/animation/fx_1_heart.exp3.json') },
      { fileName: 'fx_10_yellowline.exp3.json', name: 'fx_10_yellowline', path: 'assets/live2d/model/animation/fx_10_yellowline.exp3.json', json: require('../assets/live2d/model/animation/fx_10_yellowline.exp3.json') },
      { fileName: 'fx_11_star.exp3.json', name: 'fx_11_star', path: 'assets/live2d/model/animation/fx_11_star.exp3.json', json: require('../assets/live2d/model/animation/fx_11_star.exp3.json') },
      { fileName: 'fx_12_zzz.exp3.json', name: 'fx_12_zzz', path: 'assets/live2d/model/animation/fx_12_zzz.exp3.json', json: require('../assets/live2d/model/animation/fx_12_zzz.exp3.json') },
      { fileName: 'fx_13_angry.exp3.json', name: 'fx_13_angry', path: 'assets/live2d/model/animation/fx_13_angry.exp3.json', json: require('../assets/live2d/model/animation/fx_13_angry.exp3.json') },
      { fileName: 'fx_2_pale2.exp3.json', name: 'fx_2_pale2', path: 'assets/live2d/model/animation/fx_2_pale2.exp3.json', json: require('../assets/live2d/model/animation/fx_2_pale2.exp3.json') },
      { fileName: 'fx_3_note.exp3.json', name: 'fx_3_note', path: 'assets/live2d/model/animation/fx_3_note.exp3.json', json: require('../assets/live2d/model/animation/fx_3_note.exp3.json') },
      { fileName: 'fx_4_sweat.exp3.json', name: 'fx_4_sweat', path: 'assets/live2d/model/animation/fx_4_sweat.exp3.json', json: require('../assets/live2d/model/animation/fx_4_sweat.exp3.json') },
      { fileName: 'fx_5_sweat_2.exp3.json', name: 'fx_5_sweat_2', path: 'assets/live2d/model/animation/fx_5_sweat_2.exp3.json', json: require('../assets/live2d/model/animation/fx_5_sweat_2.exp3.json') },
      { fileName: 'fx_6_surprised.exp3.json', name: 'fx_6_surprised', path: 'assets/live2d/model/animation/fx_6_surprised.exp3.json', json: require('../assets/live2d/model/animation/fx_6_surprised.exp3.json') },
      { fileName: 'fx_7_question.exp3.json', name: 'fx_7_question', path: 'assets/live2d/model/animation/fx_7_question.exp3.json', json: require('../assets/live2d/model/animation/fx_7_question.exp3.json') },
      { fileName: 'fx_8_exclamation.exp3.json', name: 'fx_8_exclamation', path: 'assets/live2d/model/animation/fx_8_exclamation.exp3.json', json: require('../assets/live2d/model/animation/fx_8_exclamation.exp3.json') },
      { fileName: 'fx_9_swirl.exp3.json', name: 'fx_9_swirl', path: 'assets/live2d/model/animation/fx_9_swirl.exp3.json', json: require('../assets/live2d/model/animation/fx_9_swirl.exp3.json') },
      { fileName: 'gonyogonyo.exp3.json', name: 'gonyogonyo', path: 'assets/live2d/model/animation/gonyogonyo.exp3.json', json: require('../assets/live2d/model/animation/gonyogonyo.exp3.json') },
      { fileName: 'highlight_onoff.exp3.json', name: 'highlight_onoff', path: 'assets/live2d/model/animation/highlight_onoff.exp3.json', json: require('../assets/live2d/model/animation/highlight_onoff.exp3.json') },
      { fileName: 'jitome.exp3.json', name: 'jitome', path: 'assets/live2d/model/animation/jitome.exp3.json', json: require('../assets/live2d/model/animation/jitome.exp3.json') },
      { fileName: 'kukkoro.exp3.json', name: 'kukkoro', path: 'assets/live2d/model/animation/kukkoro.exp3.json', json: require('../assets/live2d/model/animation/kukkoro.exp3.json') },
      { fileName: 'oo.exp3.json', name: 'oo', path: 'assets/live2d/model/animation/oo.exp3.json', json: require('../assets/live2d/model/animation/oo.exp3.json') },
      { fileName: 'pale.exp3.json', name: 'pale', path: 'assets/live2d/model/animation/pale.exp3.json', json: require('../assets/live2d/model/animation/pale.exp3.json') },
      { fileName: 'perori.exp3.json', name: 'perori', path: 'assets/live2d/model/animation/perori.exp3.json', json: require('../assets/live2d/model/animation/perori.exp3.json') },
      { fileName: 'sleep.exp3.json', name: 'sleep', path: 'assets/live2d/model/animation/sleep.exp3.json', json: require('../assets/live2d/model/animation/sleep.exp3.json') },
      { fileName: 'smile.exp3.json', name: 'smile', path: 'assets/live2d/model/animation/smile.exp3.json', json: require('../assets/live2d/model/animation/smile.exp3.json') },
      { fileName: 'surprised.exp3.json', name: 'surprised', path: 'assets/live2d/model/animation/surprised.exp3.json', json: require('../assets/live2d/model/animation/surprised.exp3.json') },
      { fileName: 'wink_L.exp3.json', name: 'wink_L', path: 'assets/live2d/model/animation/wink_L.exp3.json', json: require('../assets/live2d/model/animation/wink_L.exp3.json') },
      { fileName: 'wink_R.exp3.json', name: 'wink_R', path: 'assets/live2d/model/animation/wink_R.exp3.json', json: require('../assets/live2d/model/animation/wink_R.exp3.json') },
      { fileName: 'XD.exp3.json', name: 'XD', path: 'assets/live2d/model/animation/XD.exp3.json', json: require('../assets/live2d/model/animation/XD.exp3.json') },
    ],
  },
  model6: {
    key: 'model6',
    renderer: 'live2d',
    label: 'Элиот',
    characterName: 'Элиот',
    displayScale: 1,
    gender: 'male',
    greeting: 'Привет, я Элиот. Можешь написать мне, отправить картинку или задать вопрос голосом.',
    ttsSpeaker: 'eugene',
    emotionProfile: model6EmotionProfile,
    webBase: '/live2d/model6',
    modelJsonPath: 'assets/live2d/model6/ellot.model3.json',
    modelJson: require('../assets/live2d/model6/ellot.model3.json'),
    mocPath: 'assets/live2d/model6/ellot.moc3',
    moc: require('../assets/live2d/model6/ellot.moc3'),
    physicsPath: 'assets/live2d/model6/ellot.physics3.json',
    physics: require('../assets/live2d/model6/ellot.physics3.json'),
    displayInfoPath: 'assets/live2d/model6/ellot.cdi3.json',
    displayInfo: require('../assets/live2d/model6/ellot.cdi3.json'),
    texturePaths: [
      'assets/live2d/model6/ellot.8192/texture_00.png',
    ],
    textures: [
      require('../assets/live2d/model6/ellot.8192/texture_00.png'),
    ],
    expressions: [
      { fileName: '게임패드.exp3.json', name: '게임패드', path: 'assets/live2d/model6/게임패드.exp3.json', json: require('../assets/live2d/model6/게임패드.exp3.json') },
      { fileName: '눈물.exp3.json', name: '눈물', path: 'assets/live2d/model6/눈물.exp3.json', json: require('../assets/live2d/model6/눈물.exp3.json') },
      { fileName: '머리안경.exp3.json', name: '머리안경', path: 'assets/live2d/model6/머리안경.exp3.json', json: require('../assets/live2d/model6/머리안경.exp3.json') },
      { fileName: '반짝눈.exp3.json', name: '반짝눈', path: 'assets/live2d/model6/반짝눈.exp3.json', json: require('../assets/live2d/model6/반짝눈.exp3.json') },
      { fileName: '얼굴안경.exp3.json', name: '얼굴안경', path: 'assets/live2d/model6/얼굴안경.exp3.json', json: require('../assets/live2d/model6/얼굴안경.exp3.json') },
      { fileName: '음침.exp3.json', name: '음침', path: 'assets/live2d/model6/음침.exp3.json', json: require('../assets/live2d/model6/음침.exp3.json') },
      { fileName: '하트눈.exp3.json', name: '하트눈', path: 'assets/live2d/model6/하트눈.exp3.json', json: require('../assets/live2d/model6/하트눈.exp3.json') },
      { fileName: '홍조.exp3.json', name: '홍조', path: 'assets/live2d/model6/홍조.exp3.json', json: require('../assets/live2d/model6/홍조.exp3.json') },
      { fileName: '화남.exp3.json', name: '화남', path: 'assets/live2d/model6/화남.exp3.json', json: require('../assets/live2d/model6/화남.exp3.json') },
    ],
  },
  robot: {
    key: 'robot',
    renderer: 'lottie',
    label: 'Вася',
    characterName: 'Вася',
    displayScale: 1,
    gender: 'male',
    greeting: 'Привет, я Вася. Я робот-помощник. Можешь написать мне, отправить картинку или задать вопрос голосом.',
    ttsSpeaker: 'aidar',
    emotionProfile: {},
    expressions: [],
  },
};

export const defaultModelKey = 'model';

export const live2dModelOptions = [
  { key: 'model', label: 'Клара' },
  { key: 'model6', label: 'Элиот' },
  { key: 'robot', label: 'Вася' },
];
