export const modelAssets = {
  modelJson: require('../assets/live2d/model/ulvm2_0001.model3.json'),
  moc: require('../assets/live2d/model/ulvm2_0001.moc3'),
  physics: require('../assets/live2d/model/ulvm2_0001.physics3.json'),
  displayInfo: require('../assets/live2d/model/ulvm2_0001.cdi3.json'),
  textures: [
    require('../assets/live2d/model/ulvm2_0001.4096/texture_00.png'),
    require('../assets/live2d/model/ulvm2_0001.4096/texture_01.png'),
    require('../assets/live2d/model/ulvm2_0001.4096/texture_02.png'),
    require('../assets/live2d/model/ulvm2_0001.4096/texture_03.png'),
    require('../assets/live2d/model/ulvm2_0001.4096/texture_04.png'),
  ],
};

export const expressionAssets = {
  'angry.exp3.json': require('../assets/live2d/model/animation/angry.exp3.json'),
  'angry2.exp3.json': require('../assets/live2d/model/animation/angry2.exp3.json'),
  'blush.exp3.json': require('../assets/live2d/model/animation/blush.exp3.json'),
  'cat_mouth.exp3.json': require('../assets/live2d/model/animation/cat_mouth.exp3.json'),
  'costume_v0000.exp3.json': require('../assets/live2d/model/animation/costume_v0000.exp3.json'),
  'costume_v0052.exp3.json': require('../assets/live2d/model/animation/costume_v0052.exp3.json'),
  'costume_v0100.exp3.json': require('../assets/live2d/model/animation/costume_v0100.exp3.json'),
  'costume_v0101.exp3.json': require('../assets/live2d/model/animation/costume_v0101.exp3.json'),
  'cry.exp3.json': require('../assets/live2d/model/animation/cry.exp3.json'),
  'fx_1_heart.exp3.json': require('../assets/live2d/model/animation/fx_1_heart.exp3.json'),
  'fx_10_yellowline.exp3.json': require('../assets/live2d/model/animation/fx_10_yellowline.exp3.json'),
  'fx_11_star.exp3.json': require('../assets/live2d/model/animation/fx_11_star.exp3.json'),
  'fx_12_zzz.exp3.json': require('../assets/live2d/model/animation/fx_12_zzz.exp3.json'),
  'fx_13_angry.exp3.json': require('../assets/live2d/model/animation/fx_13_angry.exp3.json'),
  'fx_2_pale2.exp3.json': require('../assets/live2d/model/animation/fx_2_pale2.exp3.json'),
  'fx_3_note.exp3.json': require('../assets/live2d/model/animation/fx_3_note.exp3.json'),
  'fx_4_sweat.exp3.json': require('../assets/live2d/model/animation/fx_4_sweat.exp3.json'),
  'fx_5_sweat_2.exp3.json': require('../assets/live2d/model/animation/fx_5_sweat_2.exp3.json'),
  'fx_6_surprised.exp3.json': require('../assets/live2d/model/animation/fx_6_surprised.exp3.json'),
  'fx_7_question.exp3.json': require('../assets/live2d/model/animation/fx_7_question.exp3.json'),
  'fx_8_exclamation.exp3.json': require('../assets/live2d/model/animation/fx_8_exclamation.exp3.json'),
  'fx_9_swirl.exp3.json': require('../assets/live2d/model/animation/fx_9_swirl.exp3.json'),
  'gonyogonyo.exp3.json': require('../assets/live2d/model/animation/gonyogonyo.exp3.json'),
  'highlight_onoff.exp3.json': require('../assets/live2d/model/animation/highlight_onoff.exp3.json'),
  'jitome.exp3.json': require('../assets/live2d/model/animation/jitome.exp3.json'),
  'kukkoro.exp3.json': require('../assets/live2d/model/animation/kukkoro.exp3.json'),
  'oo.exp3.json': require('../assets/live2d/model/animation/oo.exp3.json'),
  'pale.exp3.json': require('../assets/live2d/model/animation/pale.exp3.json'),
  'perori.exp3.json': require('../assets/live2d/model/animation/perori.exp3.json'),
  'sleep.exp3.json': require('../assets/live2d/model/animation/sleep.exp3.json'),
  'smile.exp3.json': require('../assets/live2d/model/animation/smile.exp3.json'),
  'surprised.exp3.json': require('../assets/live2d/model/animation/surprised.exp3.json'),
  'wink_L.exp3.json': require('../assets/live2d/model/animation/wink_L.exp3.json'),
  'wink_R.exp3.json': require('../assets/live2d/model/animation/wink_R.exp3.json'),
  'XD.exp3.json': require('../assets/live2d/model/animation/XD.exp3.json'),
};

